/**
 * src/pulse/lib/conflictDetector.ts
 * Detects overlapping calendar events and uses LLM to suggest resolutions.
 *
 * Key function: detectConflicts(runtime, events) → ConflictResult[]
 *
 * A conflict is any two non-all-day events whose time ranges overlap by any
 * amount. Resolution suggestions are generated by the LLM (TEXT_SMALL) with
 * a regex fallback that returns a generic reschedule recommendation.
 */

import { ModelType } from "@elizaos/core";
import type { IAgentRuntime } from "@elizaos/core";
import { eventsOverlap, type CalendarEvent } from "./calendarClient.js";

// ─── Public Types ─────────────────────────────────────────────────────────────

export interface ConflictResult {
  /** First overlapping event */
  eventA: CalendarEvent;
  /** Second overlapping event */
  eventB: CalendarEvent;
  /**
   * Overlap duration in minutes (positive integer).
   * Useful for prioritising which conflicts to surface first.
   */
  overlapMinutes: number;
  /**
   * Human-readable resolution suggestion from LLM (or fallback).
   * Example: "Reschedule 'Team sync' to 3pm — it has fewer attendees."
   */
  suggestion: string;
}

// ─── Conflict Detection ───────────────────────────────────────────────────────

/**
 * Find all pairwise overlapping events in `events` and generate a resolution
 * suggestion for each conflict.
 *
 * @param runtime  ElizaOS runtime — used for LLM calls.
 * @param events   Flat list of CalendarEvent (already filtered to a time window).
 * @returns        Array of ConflictResult, one per overlapping pair.
 */
export async function detectConflicts(
  runtime: IAgentRuntime,
  events: CalendarEvent[]
): Promise<ConflictResult[]> {
  // Find all overlapping pairs.
  const pairs: Array<[CalendarEvent, CalendarEvent]> = [];

  for (let i = 0; i < events.length; i++) {
    for (let j = i + 1; j < events.length; j++) {
      const a = events[i]!;
      const b = events[j]!;
      if (eventsOverlap(a, b)) {
        pairs.push([a, b]);
      }
    }
  }

  if (pairs.length === 0) return [];

  // Generate suggestions in parallel (bounded by pairs count — typically small).
  return Promise.all(
    pairs.map(async ([a, b]) => {
      const overlapMinutes = computeOverlapMinutes(a, b);
      const suggestion = await resolveSuggestion(runtime, a, b);
      return { eventA: a, eventB: b, overlapMinutes, suggestion };
    })
  );
}

// ─── Overlap Calculation ──────────────────────────────────────────────────────

function computeOverlapMinutes(a: CalendarEvent, b: CalendarEvent): number {
  const aStart = new Date(a.start).getTime();
  const aEnd   = new Date(a.end).getTime();
  const bStart = new Date(b.start).getTime();
  const bEnd   = new Date(b.end).getTime();

  const overlapStart = Math.max(aStart, bStart);
  const overlapEnd   = Math.min(aEnd, bEnd);
  const ms           = Math.max(0, overlapEnd - overlapStart);

  return Math.round(ms / 60_000);
}

// ─── Resolution Suggestion ────────────────────────────────────────────────────

async function resolveSuggestion(
  runtime: IAgentRuntime,
  a: CalendarEvent,
  b: CalendarEvent
): Promise<string> {
  try {
    return await llmSuggestion(runtime, a, b);
  } catch {
    return fallbackSuggestion(a, b);
  }
}

async function llmSuggestion(
  runtime: IAgentRuntime,
  a: CalendarEvent,
  b: CalendarEvent
): Promise<string> {
  const fmt = (ev: CalendarEvent) =>
    `"${ev.title}" (${ev.start.slice(11, 16)}–${ev.end.slice(11, 16)}` +
    (ev.attendees.length ? `, ${ev.attendees.length} attendees` : "") +
    ")";

  const prompt =
    `Two calendar events overlap. Suggest a one-sentence resolution (reschedule one, ` +
    `decline one, or shorten one).\n\n` +
    `Event A: ${fmt(a)}\n` +
    `Event B: ${fmt(b)}\n\n` +
    `Reply with ONE sentence only. No preamble.`;

  const raw = await runtime.useModel(ModelType.TEXT_SMALL, {
    prompt,
    maxTokens: 80,
    temperature: 0.3,
  });

  const suggestion = raw.trim().replace(/^["']|["']$/g, "").trim();
  if (!suggestion || suggestion.length < 10) throw new Error("empty response");
  return suggestion;
}

function fallbackSuggestion(a: CalendarEvent, b: CalendarEvent): string {
  // Pick the event with fewer attendees to reschedule (less disruption).
  const reschedule =
    (a.attendees.length ?? 0) <= (b.attendees.length ?? 0) ? a : b;
  const aTime = a.start.slice(11, 16);
  const bTime = b.start.slice(11, 16);
  return (
    `"${a.title}" (${aTime}) and "${b.title}" (${bTime}) overlap — ` +
    `consider rescheduling "${reschedule.title}" to avoid the conflict.`
  );
}
